import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar/Navbar";
import { Toaster } from "react-hot-toast";

const kumbhSans = Kumbh_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-kumbh-sans",
});

export const metadata: Metadata = {
  title: "Sneakers - OJ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kumbhSans.variable} font-sans`}>
        <Navbar />
        {children}
        <Toaster
          position="bottom-center"
          toastOptions={{
            success: {
              iconTheme: {
                primary: "hsl(26, 100%, 55%)",
                secondary: "hsl(25, 100%, 94%)",
              },
            },
            style: {
              padding: "8px",
              color: "hsl(26, 100%, 55%)",
              background: "hsl(25, 100%, 94%)",
              fontWeight: 500,
            },
            duration: 2000,
          }}
        />
      </body>
    </html>
  );
}
